pub const WORLD_SEED: u64 = 12345;

pub const SAVE_ROOT_DIR: &str = "saves";
pub const SETTINGS_FILE_NAME: &str = "settings.cfg";
pub const DEFAULT_WORLD_DIR: &str = "default_world";
pub const CHUNK_SAVE_FILE_NAME: &str = "chunks.aqchunks";

pub const DEFAULT_MOUSE_SENSITIVITY: f32 = 0.0025;
pub const MIN_MOUSE_SENSITIVITY: f32 = 0.0001;
pub const MAX_MOUSE_SENSITIVITY: f32 = 0.05;

pub const DEFAULT_FOV_DEGREES: f32 = 70.0;
pub const MIN_FOV_DEGREES: f32 = 50.0;
pub const MAX_FOV_DEGREES: f32 = 110.0;

pub const DEFAULT_RENDER_CHUNK_DISTANCE: i32 = 32;
pub const MIN_RENDER_CHUNK_DISTANCE: i32 = 8;
pub const MAX_RENDER_CHUNK_DISTANCE: i32 = 256;

pub const PLAYER_CROUCH_SPEED: f32 = 3.0;
pub const PLAYER_WALK_SPEED: f32 = 5.5;
pub const PLAYER_SPRINT_SPEED: f32 = 8.5;
pub const PLAYER_IN_AIR_MOVE_SPEED: f32 = 2.0;
pub const PLAYER_MOVE_ACCELERATION: f32 = 24.0;
pub const PLAYER_GROUND_SUPPORT_DISTANCE: f32 = 0.01;
pub const PLAYER_JUMP_HEIGHT: f32 = 1.35;
pub const PLAYER_GRAVITY: f32 = 24.0;
pub const PLAYER_MAX_FALL_SPEED: f32 = 48.0;

pub const NOCLIP_WALK_SPEED: f32 = 18.0;
pub const NOCLIP_FAST_SPEED: f32 = 42.0;

pub const MAX_ACTIVE_WORLD_CHUNKS: usize = 4096;
pub const MAX_RENDERED_CHUNK_MESHES: usize = 1024;
pub const MAX_STREAMING_COORDS_PER_CENTER: usize = 32768;
pub const MAX_NEW_RENDER_MESHES_QUEUED_PER_FRAME: usize = 8;
pub const MAX_DIRTY_MESH_QUEUE_BACKLOG: usize = 2048;
pub const MAX_PENDING_NORMAL_MESH_JOBS: usize = 8;
pub const MAX_PENDING_GENERATION_JOBS: usize = 8;
pub const MAX_CHUNK_JOB_RESULTS_PROCESSED_PER_FRAME: usize = 6;
pub const DIRTY_MESH_JOBS_PER_FRAME: usize = 1;
pub const CHUNK_GENERATION_JOBS_PER_FRAME: usize = 1;
pub const INITIAL_WORLD_PRELOAD_CHUNK_LIMIT: usize = 2048;
pub const LOADING_CHUNKS_GENERATED_PER_FRAME: usize = 16;
pub const LOADING_MESH_JOBS_QUEUED_PER_FRAME: usize = 8;
pub const MAX_LOADING_MESH_JOBS_PENDING: usize = 16;
pub const LOADING_CHUNK_JOB_RESULTS_PROCESSED_PER_FRAME: usize = 16;

pub const STREAMING_RAY_GRID_COLUMNS: usize = 17;
pub const STREAMING_RAY_GRID_ROWS: usize = 11;
pub const STREAMING_NEAR_CHUNK_RADIUS: i32 = 2;
pub const STREAMING_VISIBLE_RAY_MIN_CHUNKS_BELOW_SURFACE: i32 = 0;
pub const STREAMING_VIEW_REBUILD_DEGREES: f32 = 4.0;
